routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::post('/uploadFiles', 'DropzoneController@uploadFiles');
Route::get('/uploadedfiles/{filename}', 'HomeController@getUploadedFiles');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'HomeController@getSearch');
Route::get('/article/{slug}', 'HomeController@viewArtcile');


Route::group(['middleware' => ['auth'], 'prefix' => 'admin','namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'adminController@index');
    Route::resource('articles', 'ArticlesController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'body'
    ];

    /**
     * Get all the tags that belong to the article.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'article_tag');
    }

    /**
     * Get all the tags that belong to the article by array.
     *
     * @return array
     */
    public function tagsList()
    {
        return $this->tags()->pluck('name')->toArray() ;
    }

    /**
     * Get article  photos array list .
     *
     * @return array
     */
    public function photosList()
    {
        return $this->photos()->pluck('name')->toArray();
    }

    /**
     * Get all the tags that belong to the article.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function photos()
    {
        return $this->HasMany(Photo::class);
    }

    public function setSlugAttribute($value)
    {
        if(!$value) $value=$this->title;
        $this->attributes['slug'] = str_replace(" ","-",$value);;
    }


    public function getUriAttribute($value)
    {
        return url('/article',$this->slug);
    }



    public function scopeFilter($query=null, $params=null)
    {
        if (isset($params['search']) && trim($params['search']) !== '') {
            $value = trim($params['search']);
            $query->where('title','like','%'. $value.'%')->OrWhere('body','like','%'.$value.'%');
        }

        return $query;

    }


}

resources/views/admin/_admin_err.blade.php
@if ($errors->any())
    <div class="bg-orange-lightest border-l-4 border-orange text-orange-dark p-4 my-4" role="alert">
        @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    </div>
@endif

resources/views/admin/_admin_layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link href="{{url('/css/tailwind.min.css')}}" rel="stylesheet">
    <link href="{{url('/css/toastr.min.css')}}" rel="stylesheet">
    <link href="{{url('/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{url('/css/select2.min.css')}}" rel="stylesheet">
    <link href="{{url('/css/dropzone.min.css')}}" rel="stylesheet">

    <title>Admin Panel</title>
    <style>
        .pagination {list-style: none; padding: 0; margin: 0}
        .pagination li{display: inline-block; padding: 1rem; border: 0.1rem solid #ccc}
        .pagination li.active{background: #6574cd; border: 0.1rem solid #6574cd;color: #fff;}
        .pagination li a{display: inline-block; text-decoration: none; width: 100%; height: 100%}

        .btn-uploaded-success{
            font-size: 1rem;
            text-align: center;
            display: inline-block ;
            cursor: pointer;
            margin: 0.4rem;
            color: #fff;
            background-color: green;
            padding: 0.4rem;
            border-radius: 0;
            text-decoration: none;
        }
        #dropzoneFileUpload {
            border: 0.5rem solid rgba(0,0,0,0.03);
            min-height: 18rem;
            -webkit-border-radius: 0.5rem;
            background: rgba(0,0,0,0.03);
            padding: 2rem;

        }
        .dropzone .dz-preview .dz-remove {
            font-size: 1rem;
            text-align: center;
            display: inline-block ;
            cursor: pointer;
            margin: 0.4rem;
            color: #fff;
            background-color: #d9534f;
            padding: 0.4rem;
            border-radius: 0;
            text-decoration: none;
        }
        .dropzone .dz-preview.dz-image-preview{padding:0.5rem}


    </style>

</head>
<body>


@include("admin._admin_nav")


<div class="container mx-auto ">
    @include("admin._admin_err")

    @yield("content")
</div>


<script src="{{ url('/js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ url('/js/toastr.min.js') }}"></script>
<script src="{{ url('/js/jquery.blockUI.js') }}"></script>
<script src="{{ url('/js/sw.js') }}"></script>
<script src="{{ url('/js/select2.full.min.js') }}"></script>
<script src="{{ url('/js/dropzone.min.js') }}"></script>
<script>

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    toastr.options = {
        "progressBar": true,
        "positionClass": "toast-bottom-full-width",
    }
    var baseUrl="{{url('/')}}";
    $(document).on('click','.loading',function() {
        var block_ele = $(this).closest('.card-block');
        block_ele.block({
            message: '<div class="loader-wrapper text-center"><span class="fa-li fa fa-spinner fa-spin fa-lg"></span></div>',
            overlayCSS: {
                backgroundColor: '#FFF',
                cursor: 'wait',
            },
            css: {
                border: 0,
                padding: 0,
                backgroundColor: 'none'
            }
        });
    });
</script>
@yield("js")

</body>
</html>

resources/views/admin/_admin_nav.blade.php
<nav class="w-full flex items-center justify-between flex-wrap bg-teal p-6">
    <div class="flex items-center flex-no-shrink text-white mr-6">
        <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
        <span class="font-semibold text-xl tracking-tight">MindValley Admin</span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
            <a href="{{route('admin.articles.index')}}" class="no-underline block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
                Articles
            </a>
            <a target="_blank" href="{{url('/')}}" class="no-underline block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
               Visit site
            </a>

        </div>
        <div>
            <a href="{{ route('logout') }}"  class="no-underline inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal hover:bg-white mt-4 lg:mt-0"
               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">  Logout </a>
        </div>
    </div>
</nav>


<form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
    {{ csrf_field() }}
</form>

resources/views/admin/articles_create.blade.php
@extends('admin._admin_layout')
@section("content")

    <a class="inline-block  my-5 no-underline bg-transparent hover:bg-blue text-blue-dark font-semibold hover:text-white py-2 px-4 border border-blue hover:border-transparent rounded" href="{{route('admin.articles.index')}}">Back To Articles List</a>

    <div class="w-full max-w card-block">

        <form id="form1"  method="POST" action="{{ route('admin.articles.store') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            @csrf
            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="title">
                   title *
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                       value="{{old('title')}}" name="title" id="title" type="text" placeholder="Title">
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="slug">
                    slug
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                       value="{{old('slug')}}" id="slug" name="slug" type="text" placeholder="Slug">
                <p class="text-dark py-3 text-xs italic">if empty , we will generate slug based on title attribute </p>
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="tags">
                    Tags
                </label>
                <select multiple="true" name="tags[]" id="tags" class="select2 shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline">
                    @foreach($tags as $tag)
                    <option {{old('tags') && in_array($tag,old('tags')) ? 'selected' : ''}}  value="{{$tag}}">{{$tag}}</option>
                    @endforeach
                </select>
                <p class="text-dark py-3 text-xs italic">type new tags and press Enter </p>
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="photos">
                    Photos
                </label>

                <div class="upload-div">
                    <div class="dropzone" id="dropzoneFileUpload"></div>
                </div>
            </div>


            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="body">
                    Text Body *
                </label>
                <textarea name="body" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" id="body" name="body" rows="5">{{old('body')}}</textarea>

            </div>
            <div class="flex items-center justify-between">
                <button class="loading bg-blue hover:bg-blue-dark text-white font-bold py-4 px-10 rounded focus:outline-none focus:shadow-outline" type="submit">
                  Post
                </button>

            </div>
        </form>

    </div>

@endsection()


@section('js')
    <script>

        $('#tags').select2({
            tags: true,
            tokenSeparators: [",", " "]
        });

        $('#form1').on('submit', function(e){
            var block_ele = $(this).closest('.card-block');
            var title = $('#title').val();
            var body = $('#body').val();
            var err="";

            if(title.length <1 ){
                err +="Please fill the title"+"<br/>";
            }
            if(body.length <1 ){
                err +="Please fill the body "+"<br/>";
            }

            if(err!=""){
                block_ele.unblock();
                toastr.error(err);
                return false;
            }

        });


        //  dropzoneFileUpload
        var maxFilesize=5 ;//mb;
        var Message ="Drag Your Photos Here , Or click inside this box for select from your computer";
        Message +="<br/>";
        Message +=" max size for each file is   "+maxFilesize+" mb ";
        Dropzone.autoDiscover = false;
        var myDropzone = new Dropzone("#dropzoneFileUpload", {
            url: baseUrl+"/uploadFiles",
            addRemoveLinks: true,
            dictCancelUpload: "Cancel",
            dictRemoveFile: "Remove",
            acceptedFiles: "image/*",
            autoProcessQueue: true,
            maxFilesize: maxFilesize, // MB
            //parallelUploads: 40,
            // uploadMultiple: true,
            dictDefaultMessage: Message,
            params: {
                _token: $('meta[name="csrf-token"]').attr('content'),
                tp: 'uploadFiles'
            },

            success: function( file, response ){
                var customButton = Dropzone.createElement('<a href>uploaded </a>');
                customButton .setAttribute("class", "btn-uploaded-success");
                file.previewTemplate.appendChild(customButton );
                file.previewElement.addEventListener("dblclick", function() {
                    window.open(baseUrl+'/uploadedfiles/'+response, '_blank');
                });

                $("#form1").append($('<input type="hidden" ' +
                    'name="files[]" ' +
                    'value="' + response + '">'));
            },
            removedfile: function(file) {
                var _ref;
                $('input[value="'+file.name+'"]').remove();
                return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
            },
        });

    </script>
@endsection()

resources/views/admin/articles_edit.blade.php
@extends('admin._admin_layout')
@section("content")

    <a class="inline-block  my-5 no-underline bg-transparent hover:bg-blue text-blue-dark font-semibold hover:text-white py-2 px-4 border border-blue hover:border-transparent rounded" href="{{route('admin.articles.index')}}">Back To Articles List</a>

    <div class="w-full max-w card-block">

        <form id="form1"  method="POST" action="{{route('admin.articles.update',$item->id) }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            @csrf
            {{ method_field('PATCH') }}

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="title">
                   title *
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                       value="{{old('title',$item->title)}}" name="title" id="title" type="text" placeholder="Title">
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="slug">
                    slug
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                       value="{{old('slug',$item->slug)}}" id="slug" name="slug" type="text" placeholder="Slug">
                <p class="text-dark py-3 text-xs italic">if empty , we will generate slug based on title attribute </p>
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="tags">
                    Tags
                </label>
                <select multiple="true" name="tags[]" id="tags" class="select2 shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline">
                    @foreach($tags as $tag)
                    <option {{$item->tagsList() && in_array($tag,$item->tagsList()) ? 'selected' : ''}}  value="{{$tag}}">{{$tag}}</option>
                    @endforeach
                </select>
                <p class="text-dark py-3 text-xs italic">type new tags and press Enter </p>
            </div>

            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="photos">
                    Photos
                </label>

                <div class="upload-div">
                    <div class="dropzone" id="dropzoneFileUpload"></div>
                </div>
            </div>


            <div class="mb-12">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="body">
                    Text Body *
                </label>
                <textarea name="body" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" id="body" name="body" rows="5">{{old('body',$item->body)}}</textarea>

            </div>
            <div class="flex items-center justify-between">
                <button class="loading bg-blue hover:bg-blue-dark text-white font-bold py-4 px-10 rounded focus:outline-none focus:shadow-outline" type="submit">
                  Post
                </button>

            </div>
        </form>

    </div>

@endsection()


@section('js')
    <script>

        $('#tags').select2({
            tags: true,
            tokenSeparators: [",", " "]
        });

        $('#form1').on('submit', function(e){
            var block_ele = $(this).closest('.card-block');
            var title = $('#title').val();
            var body = $('#body').val();
            var err="";

            if(title.length <1 ){
                err +="Please fill the title"+"<br/>";
            }
            if(body.length <1 ){
                err +="Please fill the body "+"<br/>";
            }

            if(err!=""){
                block_ele.unblock();
                toastr.error(err);
                return false;
            }

        });


        //  dropzoneFileUpload
        var maxFilesize=5 ;//mb;
        var Message ="Drag Your Photos Here , Or click inside this box for select from your computer";
        Message +="<br/>";
        Message +=" max size for each file is   "+maxFilesize+" mb ";
        Dropzone.autoDiscover = false;
        var myDropzone = new Dropzone("#dropzoneFileUpload", {
            url: baseUrl+"/uploadFiles",
            addRemoveLinks: true,
            dictCancelUpload: "Cancel",
            dictRemoveFile: "Remove",
            acceptedFiles: "image/*",
            autoProcessQueue: true,
            maxFilesize: maxFilesize, // MB
            //parallelUploads: 40,
            // uploadMultiple: true,
            dictDefaultMessage: Message,
            params: {
                _token: $('meta[name="csrf-token"]').attr('content'),
                tp: 'uploadFiles'
            },

            success: function( file, response ){
                var customButton = Dropzone.createElement('<a href>uploaded </a>');
                customButton .setAttribute("class", "btn-uploaded-success");
                file.previewTemplate.appendChild(customButton );
                file.previewElement.addEventListener("dblclick", function() {
                    window.open(baseUrl+'/uploadedfiles/'+response, '_blank');
                });

                $("#form1").append($('<input type="hidden" ' +
                    'name="files[]" ' +
                    'value="' + response + '">'));
            },
            removedfile: function(file) {
                var _ref;
                $('input[value="'+file.name+'"]').remove();
                return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
            },
        });



    </script>


    @if(old('files',isset($item->photos)))
        <script type="text/javascript">
            $(function() {
                var mockFile ;
                @foreach (old('files',isset($item) ? $item->photosList() : null) as $uploadedPhoto)
                    mockFile = { name: "{{$uploadedPhoto}}", size: 12345, type: 'image/jpeg' };
                myDropzone.options.addedfile.call(myDropzone, mockFile);
                myDropzone.options.thumbnail.call(myDropzone, mockFile, baseUrl+"/uploadedfiles/"+"{{$uploadedPhoto}}");
                mockFile.previewElement.classList.add('dz-success');
                mockFile.previewElement.classList.add('dz-complete');

                var elem=$('<input type="hidden" ' +
                    'name="files[]" ' +
                    'value="' + 1 + '">');
                myDropzone.emit("loadfile", mockFile);

                $("#form1").append('<input type="hidden" ' +
                    'name="files[]" ' +
                    'value="{{$uploadedPhoto}}">');

                @endforeach

            })
        </script>
    @endif
@endsection()

resources/views/admin/articles_list.blade.php
@extends('admin._admin_layout')
@section("content")

    <div class="max-w rounded shadow-lg p-5  my-5 ">
    <a class="inline-block no-underline my-5  bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded" href="{{route('admin.articles.create')}}">Create New Article</a>
    <table class="text-left my-4 w-full " style="border-collapse:collapse">
        <thead>
        <tr>
            <th class="py-4 px-6 bg-grey-lighter font-sans font-medium uppercase text-sm text-grey border-b border-grey-light">title</th>
            <th class="py-4 px-6 bg-grey-lighter font-sans font-medium uppercase text-sm text-grey border-b border-grey-light">created at</th>
            <th class="py-4 px-6 bg-grey-lighter font-sans font-medium uppercase text-sm text-grey border-b border-grey-light"></th>
        </tr>
        </thead>
        <tbody>

        @forelse($items as $item)
        <tr class="hover:bg-blue-lightest card-block">
            <td class="py-4 px-6 border-b border-grey-light"><a target="_blank" href="{{$item->uri}}">{{$item->title}}</a> </td>
            <td class="py-4 px-6 border-b border-grey-light text-center">{{$item->created_at}}</td>
            <td class="py-4 px-6 border-b border-grey-light text-center">
                <a class="inline-block no-underline m-5  bg-blue hover:bg-blue-dark text-white p-2 rounded" href="{{route('admin.articles.edit',$item->id)}}">Edit</a>
                <a class="loading btn-delete inline-block no-underline m-5  bg-red hover:bg-red-dark text-white p-2 rounded"
                   data-id="{{$item->id}}" data-path="{{route('admin.articles.destroy',$item->id)}}" href> Remove </a>
            </td>
        </tr>
        @empty
            <td colspan="3" class="py-4 px-6 border-b border-grey-light">There is nothing to show here right now...</td>
        @endforelse

        </tbody>
    </table>
    </div>
@endsection()


@section('js')
    <script>
        $(document).on('click','.btn-delete',function(e) {
            e.preventDefault();
            var block_ele = $(this).closest('.card-block');
            var btn = $(this);
            var id = $(this).attr('data-id');
            var path = $(this).attr('data-path');

            swal({
                title: 'Warning',
                text: 'You are removing an article !',
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes Remove it '
            }).then(function(result) {
                if (result.value) {
                    $.ajax({
                        url :path,
                        type: "DELETE",
                        data:{id:id},
                    }).done(function (response) {
                        if(response.status){
                            toastr.success(response.message);
                            btn.closest("tr").remove();
                        }
                        else
                            toastr.error(response.message);

                    }).fail(function (xhr, status, error) {
                        console.log(error);
                        toastr.error(error);
                    });

                }
            })

            block_ele.unblock();


        });


    </script>
@endsection()